"""
BTC Bias Engine -- Unified Launcher

Modes (pass as first argument):
    --engine     Run the trading engine headless (writes to data/engine_history.log)
    --monitor    Open the live terminal monitor (reads data/dashboard_state.json)
    --setup      Interactive first-run setup: configures Kalshi credentials
    (no flag)    Opens a menu that lets the user pick engine / monitor / setup

No secrets are baked in. The engine reads credentials from:
    credentials/kalshi.env
with:
    KALSHI_API_KEY=<your-uuid>
    KALSHI_PRIVATE_KEY_PATH=credentials/kalshi_key.pem
"""
import multiprocessing
import os
import sys
import traceback


def _resolve_base():
    """Return the directory where the engine files live."""
    if getattr(sys, "frozen", False):
        return os.path.dirname(sys.executable)
    return os.path.dirname(os.path.abspath(__file__))


def _credentials_present(base):
    env_path = os.path.join(base, "credentials", "kalshi.env")
    if not os.path.exists(env_path):
        return False
    try:
        with open(env_path, "r", encoding="utf-8") as f:
            content = f.read()
        has_key = "KALSHI_API_KEY=" in content and not _line_empty(content, "KALSHI_API_KEY=")
        has_pem = "KALSHI_PRIVATE_KEY_PATH=" in content and not _line_empty(content, "KALSHI_PRIVATE_KEY_PATH=")
        return has_key and has_pem
    except Exception:
        return False


def _line_empty(content, prefix):
    for line in content.splitlines():
        line = line.strip()
        if line.startswith(prefix):
            val = line.split("=", 1)[1].strip()
            return val == "" or val.startswith("<")
    return True


def _run_setup(base):
    """Interactive first-run setup: prompts for Kalshi UUID and PEM path."""
    cred_dir = os.path.join(base, "credentials")
    os.makedirs(cred_dir, exist_ok=True)
    env_path = os.path.join(cred_dir, "kalshi.env")

    print("=" * 60)
    print("  BTC Bias Engine -- First-Run Setup")
    print("=" * 60)
    print()
    print("You need:")
    print("  1. A Kalshi API key UUID")
    print("     Get one at: https://kalshi.com/account/settings/api")
    print("  2. The RSA private key (.pem file) downloaded from Kalshi")
    print()

    while True:
        key_uuid = input("Kalshi API key UUID: ").strip()
        if len(key_uuid) >= 8 and "-" in key_uuid:
            break
        print("  That doesn't look like a UUID. Try again (or Ctrl+C to exit).")

    while True:
        pem_path = input("Path to your .pem file (absolute or relative): ").strip().strip('"')
        if not pem_path:
            print("  Path required.")
            continue
        if not os.path.isabs(pem_path):
            candidate = os.path.abspath(os.path.join(base, pem_path))
        else:
            candidate = os.path.abspath(pem_path)
        if not os.path.exists(candidate):
            print(f"  File not found: {candidate}")
            continue
        # Copy PEM into credentials/ if it's outside the app dir
        target_pem = os.path.join(cred_dir, "kalshi_key.pem")
        if os.path.abspath(candidate) != os.path.abspath(target_pem):
            try:
                import shutil
                shutil.copy2(candidate, target_pem)
                print(f"  Copied PEM to {target_pem}")
            except Exception as e:
                print(f"  WARNING: could not copy PEM ({e}); using original path")
                target_pem = candidate
        break

    rel_pem = os.path.relpath(target_pem, base).replace("\\", "/")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# BTC Bias Engine -- Kalshi credentials\n")
        f.write("# Generated by setup wizard. Never share this file.\n")
        f.write(f"KALSHI_API_KEY={key_uuid}\n")
        f.write(f"KALSHI_PRIVATE_KEY_PATH={rel_pem}\n")
        f.write("KALSHI_DEMO=false\n")
        f.write("EXECUTE_TRADES=true\n")

    print()
    print(f"  Saved: {env_path}")
    print()
    print("You can now run:")
    print("  BTC_Engine.exe --engine    (starts the trading engine)")
    print("  BTC_Engine.exe --monitor   (live terminal monitor)")
    print()


def _run_engine(base):
    """Headless trading loop. Crash log at data/engine_crash.log."""
    crash_log = os.path.join(base, "data", "engine_crash.log")
    try:
        # Load credentials into env before engine imports
        env_path = os.path.join(base, "credentials", "kalshi.env")
        if os.path.exists(env_path):
            with open(env_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    k, v = line.split("=", 1)
                    k = k.strip()
                    v = v.strip().strip('"').strip("'")
                    # Resolve relative PEM path to absolute
                    if k == "KALSHI_PRIVATE_KEY_PATH" and not os.path.isabs(v):
                        v = os.path.abspath(os.path.join(base, v))
                    os.environ[k] = v
        import run_copy_engine
        import asyncio
        asyncio.run(run_copy_engine.main())
    except Exception:
        with open(crash_log, "a", encoding="utf-8") as f:
            f.write(f"\n{'='*60}\n")
            f.write(f"ENGINE CRASH at {__import__('datetime').datetime.now()}\n")
            traceback.print_exc(file=f)
        raise


def _run_monitor(base):
    """Live terminal monitor."""
    try:
        import monitor
        monitor.main()
    except AttributeError:
        # Older monitor.py runs at import-time; just import it
        import monitor  # noqa: F401
    except KeyboardInterrupt:
        pass


def _show_menu(base):
    """Interactive mode-picker when no flag is passed."""
    creds_ok = _credentials_present(base)
    print("=" * 60)
    print("  BTC Bias Engine")
    print("=" * 60)
    print()
    if not creds_ok:
        print("  No Kalshi credentials found. Running setup first...")
        print()
        _run_setup(base)
        creds_ok = _credentials_present(base)
        if not creds_ok:
            print("  Setup incomplete. Exiting.")
            return

    print("  1) Run trading engine (headless)")
    print("  2) Open live monitor (read-only terminal dashboard)")
    print("  3) Re-run setup / change credentials")
    print("  Q) Quit")
    print()
    choice = input("  Choice [1/2/3/Q]: ").strip().lower()
    if choice == "1":
        _run_engine(base)
    elif choice == "2":
        _run_monitor(base)
    elif choice == "3":
        _run_setup(base)
    else:
        return


def main():
    multiprocessing.freeze_support()
    base = _resolve_base()
    os.chdir(base)

    if base not in sys.path:
        sys.path.insert(0, base)

    os.makedirs(os.path.join(base, "data"), exist_ok=True)
    os.makedirs(os.path.join(base, "credentials"), exist_ok=True)

    # Drop an example env if none present
    example_path = os.path.join(base, "credentials", "kalshi.env.example")
    if not os.path.exists(example_path):
        try:
            with open(example_path, "w", encoding="utf-8") as f:
                f.write("# Rename this file to kalshi.env and fill in your values.\n")
                f.write("KALSHI_API_KEY=<your-kalshi-uuid-here>\n")
                f.write("KALSHI_PRIVATE_KEY_PATH=credentials/kalshi_key.pem\n")
                f.write("KALSHI_DEMO=false\n")
                f.write("EXECUTE_TRADES=true\n")
        except Exception:
            pass

    if "--engine" in sys.argv:
        _run_engine(base)
    elif "--monitor" in sys.argv:
        _run_monitor(base)
    elif "--setup" in sys.argv:
        _run_setup(base)
    else:
        _show_menu(base)


if __name__ == "__main__":
    main()
