"""Terminal Wallet Copy — independent late-window copy engine.

Watches a curated list of high-WR Polymarket BTC up/down wallets and
mirrors their late-window buys onto Kalshi at bid+1c with a fixed
dollar size. Designed to run *in parallel* with the FVG (TA_FORCED)
engine — they don't share gating logic, so this tier fires only when
a tracked wallet does, regardless of pressure / DOMINANT / RSI / etc.

The wallet population is generated by
``scripts/identify_terminal_wallets.py`` and stored in
``data/terminal_wallets.json``. This module loads that file at engine
startup (and reloads on a schedule), polls Polymarket trades every
``WALLET_COPY_POLL_S`` seconds for new fills by tracked wallets, and
fires a single Kalshi BUY on any qualifying signal.

Design constraints (per user 2026-04-29):
    - $20 per trade (configurable via WALLET_COPY_DOLLAR_SIZE)
    - Entry price = current Kalshi best-bid + 1c (so taker fills
      immediately if depth exists, otherwise rests as new top bid
      and accumulates on dips)
    - No FVG / pressure / RSI / DOMINANT gates — the wallet's
      selectivity IS the filter
    - One copy per Kalshi window max
    - Hold to settlement (no stop) — these are >=95% WR signals
    - Per-day cap to bound exposure
"""
from __future__ import annotations

import asyncio
import json
import logging
import time
from pathlib import Path
from typing import Optional

import aiohttp

logger = logging.getLogger(__name__)

POLY_DATA_API = "https://data-api.polymarket.com"

# Where the offline scanner saves the qualifying wallet list
WALLET_LIST_PATH = Path(__file__).parent / "data" / "terminal_wallets.json"

# Wallet tier names (used as keys throughout)
TIER_CERTAINTY = "CERTAINTY"
TIER_MID = "MID"
TIER_CONTRARIAN = "CONTRARIAN"


def _uc(key: str, default):
    """Late-binding config lookup (matches polymarket_copy_engine pattern)."""
    try:
        from polymarket_copy_engine import _user_cfg
        return _user_cfg.get(key, default)
    except Exception:
        return default


def _classify_tier(avg_price: float) -> str:
    """Classify wallet into pricing tier from volume-weighted avg_price."""
    cert_min = float(_uc("WALLET_COPY_TIER_CERTAINTY_MIN", 0.85))
    mid_min = float(_uc("WALLET_COPY_TIER_MID_MIN", 0.50))
    if avg_price >= cert_min:
        return TIER_CERTAINTY
    if avg_price >= mid_min:
        return TIER_MID
    return TIER_CONTRARIAN


def _tier_premium_c(tier: str) -> Optional[int]:
    """Return per-tier premium cap in cents (None = no relative cap)."""
    if tier == TIER_CERTAINTY:
        v = _uc("WALLET_COPY_CERTAINTY_PREMIUM_C", None)
        return None if v is None else int(v)
    if tier == TIER_MID:
        return int(_uc("WALLET_COPY_MID_PREMIUM_C", 10))
    return int(_uc("WALLET_COPY_CONTRARIAN_PREMIUM_C", 5))


def _tier_min_poly(tier: str) -> float:
    """Return per-tier poly_price floor."""
    if tier == TIER_CERTAINTY:
        return float(_uc("WALLET_COPY_CERTAINTY_MIN_POLY", 0.93))
    if tier == TIER_MID:
        return float(_uc("WALLET_COPY_MID_MIN_POLY", 0.50))
    return float(_uc("WALLET_COPY_CONTRARIAN_MIN_POLY", 0.30))


# ── Wallet pool loader ──────────────────────────────────────────────────────

class WalletPool:
    """Loads + holds the qualifying wallets from terminal_wallets.json."""

    def __init__(self, path: Path = WALLET_LIST_PATH):
        self.path = path
        self.addrs: set[str] = set()
        self.metadata: dict[str, dict] = {}
        self.loaded_at: float = 0.0

    def load(self) -> int:
        try:
            data = json.loads(self.path.read_text())
        except FileNotFoundError:
            logger.warning(
                "terminal_copy: %s not found — wallet pool empty. "
                "Run scripts/identify_terminal_wallets.py to generate.",
                self.path,
            )
            return 0
        except Exception as e:
            logger.error("terminal_copy: failed to load %s: %s", self.path, e)
            return 0

        # 2026-04-29 (Claude per user "any single 100% WR wallet"):
        # apply runtime quality filter on top of the file's pre-filter.
        # The file ships with min_wr=0.95, min_trades=5 — we tighten to
        # the user's stricter criteria here so the same data file can
        # serve different deployment configs.
        min_wr = float(_uc("WALLET_COPY_MIN_WR", 1.0))
        min_trades = int(_uc("WALLET_COPY_MIN_TRADES", 10))

        wallets = data.get("wallets", [])
        addrs = set()
        metadata = {}
        kept = 0
        skipped_wr = 0
        skipped_n = 0
        tier_counts = {TIER_CERTAINTY: 0, TIER_MID: 0, TIER_CONTRARIAN: 0}
        tier_pricing_on = bool(_uc("WALLET_COPY_TIER_PRICING_ENABLED", True))
        for w in wallets:
            addr = (w.get("wallet") or "").lower()
            if not addr:
                continue
            wr = float(w.get("wr", 0.0))
            n = int(w.get("trades", 0))
            if wr < min_wr:
                skipped_wr += 1
                continue
            if n < min_trades:
                skipped_n += 1
                continue
            # 2026-04-29 (Claude per user "Contrarian wallets with a 100% WR??"):
            # Compute volume-weighted avg_price from total_notional / total_size.
            # The file ships avg_size + avg_notional_usd both as
            # /n_trades means, so the ratio equals total_notional/total_size
            # (= true volume-weighted avg entry price the wallet pays).
            try:
                avg_size = float(w.get("avg_size", 0) or 0)
                avg_notional = float(w.get("avg_notional_usd", 0) or 0)
                avg_price = (avg_notional / avg_size) if avg_size > 0 else 0.0
            except (TypeError, ValueError, ZeroDivisionError):
                avg_price = 0.0
            tier = (_classify_tier(avg_price)
                    if tier_pricing_on else TIER_CERTAINTY)
            # Mutate a copy so we don't pollute the source dict
            wm = dict(w)
            wm["avg_price"] = round(avg_price, 4)
            wm["tier"] = tier
            addrs.add(addr)
            metadata[addr] = wm
            tier_counts[tier] += 1
            kept += 1
        self.addrs = addrs
        self.metadata = metadata
        self.loaded_at = time.time()
        logger.warning(
            "terminal_copy: loaded %d wallets (filter: WR>=%.2f, trades>=%d) "
            "[file had %d total; %d below WR, %d below sample] "
            "tiers: %d CERTAINTY / %d MID / %d CONTRARIAN  "
            "(generated_at=%s, tier_pricing=%s)",
            kept, min_wr, min_trades, len(wallets), skipped_wr, skipped_n,
            tier_counts[TIER_CERTAINTY], tier_counts[TIER_MID],
            tier_counts[TIER_CONTRARIAN],
            data.get("generated_at", "?")[:19], tier_pricing_on,
        )
        return len(addrs)


# ── Trade poller ────────────────────────────────────────────────────────────

class TradePoller:
    """Polls Polymarket /trades endpoint and emits new wallet-copy signals.

    Polymarket's /trades doesn't filter by user, so we pull the
    most-recent N trades each cycle and filter client-side. We dedup
    by (transactionHash, asset) so we never emit the same trade twice.
    """

    def __init__(self, session: aiohttp.ClientSession, pool: WalletPool):
        self.session = session
        self.pool = pool
        # Keep last 5000 fill ids seen so we don't re-emit
        self.seen_ids: set[str] = set()
        self.seen_order: list[str] = []
        self.last_poll_ts: float = 0.0

    async def poll_once(self) -> list[dict]:
        """Returns list of new qualifying wallet trades (raw Polymarket format)."""
        if not self.pool.addrs:
            return []
        # Pull recent trades (Polymarket returns most-recent first)
        # 2026-04-29 (Claude): bumped from 200 → 500 limit. Polymarket
        # has thousands of trades per minute across all markets and our
        # wallet pool is rare-firing. 200 trades likely only covers
        # last 30-60s, so a single missed poll could lose a wallet
        # signal forever. 500 gives 2-3x headroom.
        try:
            async with self.session.get(
                f"{POLY_DATA_API}/trades",
                params={"limit": 500, "takerOnly": "false"},
                timeout=aiohttp.ClientTimeout(total=10),
            ) as r:
                if r.status != 200:
                    return []
                trades = await r.json()
        except Exception as e:
            logger.debug("terminal_copy: poll error: %s", e)
            return []
        if not isinstance(trades, list):
            return []

        new_trades: list[dict] = []
        for t in trades:
            wallet = (t.get("proxyWallet") or "").lower()
            if not wallet or wallet not in self.pool.addrs:
                continue
            if (t.get("side") or "").upper() != "BUY":
                continue
            tx = (t.get("transactionHash") or "") + ":" + str(t.get("asset") or "")
            if not tx or tx in self.seen_ids:
                continue
            new_trades.append(t)
            self.seen_ids.add(tx)
            self.seen_order.append(tx)

        # Trim seen-id ring buffer
        while len(self.seen_order) > 5000:
            old = self.seen_order.pop(0)
            self.seen_ids.discard(old)

        self.last_poll_ts = time.time()
        return new_trades


# ── Signal qualification ────────────────────────────────────────────────────

def _slug_is_btc_market(slug: str) -> bool:
    s = (slug or "").lower()
    return "btc-updown-15m-" in s or "btc-updown-5m-" in s


def _classify_outcome_to_kalshi_side(outcome: str) -> Optional[str]:
    """Map Polymarket 'Up'/'Down' to Kalshi 'yes'/'no'."""
    o = (outcome or "").lower().strip()
    if o == "up":
        return "yes"
    if o == "down":
        return "no"
    return None


def _signal_qualifies(t: dict, pool: Optional["WalletPool"] = None) -> Optional[dict]:
    """Filter trade to a tradeable signal. Returns enriched dict or None.

    Logs every tracked-wallet trade (qualifying OR not) so we have
    observability into how many of our wallets are firing in the wild
    and which filters they hit. Without this, "no fires" is opaque —
    it could mean no trades, all trades on wrong markets, or all
    trades below the price floor.

    When `pool` is provided and TIER_PRICING is enabled, the min_price
    floor is per-tier: CERTAINTY wallets need 0.93+, MID 0.50+,
    CONTRARIAN 0.30+. Otherwise the global floor applies.
    """
    slug = t.get("slug") or t.get("eventSlug") or ""
    wallet = (t.get("proxyWallet") or "").lower()
    side_raw = t.get("outcome") or ""
    try:
        price = float(t.get("price") or 0)
        size = float(t.get("size") or 0)
    except (TypeError, ValueError):
        price = 0.0
        size = 0.0
    pseudo = t.get("pseudonym") or wallet[:12]

    if not _slug_is_btc_market(slug):
        logger.info(
            "terminal_copy WALLET-SKIP: %s (%s) traded %s on non-BTC "
            "market %s @ %.3fx%.0f",
            wallet[:12], pseudo[:18], side_raw, slug[:50], price, size,
        )
        return None
    side = _classify_outcome_to_kalshi_side(side_raw)
    if side is None:
        logger.info(
            "terminal_copy WALLET-SKIP: %s outcome=%s unrecognized "
            "(slug=%s)", wallet[:12], side_raw, slug[:50],
        )
        return None

    # Per-tier or global poly-price floor
    tier = TIER_CERTAINTY
    tier_pricing_on = bool(_uc("WALLET_COPY_TIER_PRICING_ENABLED", True))
    if tier_pricing_on and pool is not None:
        meta = pool.metadata.get(wallet, {})
        tier = meta.get("tier", TIER_CERTAINTY)
        min_price = _tier_min_poly(tier)
    else:
        min_price = float(_uc("WALLET_COPY_MIN_POLY_PRICE", 0.93))
    min_size = float(_uc("WALLET_COPY_MIN_POLY_SIZE", 5.0))
    if price < min_price:
        logger.info(
            "terminal_copy WALLET-SKIP: %s (%s) [%s] price=%.3f < "
            "tier_min=%.3f side=%s slug=%s",
            wallet[:12], pseudo[:18], tier, price, min_price,
            side_raw, slug[:50],
        )
        return None
    if size < min_size:
        logger.info(
            "terminal_copy WALLET-SKIP: %s (%s) [%s] size=%.0f < min=%.0f "
            "side=%s slug=%s @ %.3f",
            wallet[:12], pseudo[:18], tier, size, min_size,
            side_raw, slug[:50], price,
        )
        return None
    logger.warning(
        "terminal_copy WALLET-QUALIFIED: %s (%s) [%s] %s %.3fx%.0f on %s",
        wallet[:12], pseudo[:18], tier, side_raw, price, size, slug[:50],
    )
    return {
        "wallet": wallet,
        "username": pseudo,
        "tier": tier,
        "kalshi_side": side,
        "poly_price": price,
        "poly_size": size,
        "poly_slug": slug,
        "poly_ts": int(t.get("timestamp") or 0),
    }


# ── Kalshi window mapping ───────────────────────────────────────────────────

def _current_kalshi_ticker(engine) -> Optional[str]:
    """Return the engine's currently-tracked Kalshi ticker, or None."""
    return getattr(engine, "_current_kalshi_ticker", "") or None


# ── Main copy loop ──────────────────────────────────────────────────────────

class TerminalCopyEngine:
    """Top-level coordinator. Wired into PolymarketCopyEngine startup."""

    def __init__(self, parent_engine):
        self.engine = parent_engine
        self.pool = WalletPool()
        # Per-window state
        self._last_signal_window: str = ""  # ticker string of last fire
        self._fires_today: int = 0
        self._fires_today_date: str = ""

    def _today_key(self) -> str:
        return time.strftime("%Y-%m-%d", time.gmtime())

    def _maybe_reset_daily(self) -> None:
        today = self._today_key()
        if today != self._fires_today_date:
            self._fires_today = 0
            self._fires_today_date = today

    async def _execute_copy(self, signal: dict) -> None:
        """Place the Kalshi mirror order at bid+1c for $WALLET_COPY_DOLLAR_SIZE."""
        ticker = _current_kalshi_ticker(self.engine)
        if not ticker:
            logger.warning(
                "terminal_copy: signal arrived but no active Kalshi "
                "ticker — skipping (wallet=%s side=%s poly=%.3f)",
                signal["wallet"][:12], signal["kalshi_side"],
                signal["poly_price"],
            )
            return

        # Time-of-window gate: only fire in the late-window slot
        try:
            _wo = float(getattr(self.engine, "_poly_window_open_time",
                                time.time()) or time.time())
            session_age = time.time() - _wo
            min_age_s = float(_uc("WALLET_COPY_MIN_SESSION_AGE_S", 600))
            if session_age < min_age_s:
                logger.info(
                    "terminal_copy: signal too early (age=%.0fs < %.0fs) "
                    "— skipping (wallet=%s side=%s)",
                    session_age, min_age_s, signal["wallet"][:12],
                    signal["kalshi_side"],
                )
                return
        except Exception:
            pass

        # Per-window dedupe
        if self._last_signal_window == ticker:
            logger.info(
                "terminal_copy: already fired on %s this window — "
                "skipping (wallet=%s side=%s)",
                ticker[-15:], signal["wallet"][:12], signal["kalshi_side"],
            )
            return

        # Per-day cap
        self._maybe_reset_daily()
        max_per_day = int(_uc("WALLET_COPY_MAX_PER_DAY", 8))
        if self._fires_today >= max_per_day:
            logger.info(
                "terminal_copy: daily cap %d reached — skipping",
                max_per_day,
            )
            return

        # Get current Kalshi book
        ws = getattr(self.engine, "_kalshi_ws", None)
        book = ws.get_book(ticker) if ws and hasattr(ws, "get_book") else None
        if book is None:
            logger.warning("terminal_copy: no WS book for %s — skipping",
                           ticker[-15:])
            return
        side = signal["kalshi_side"]
        if side == "yes":
            best_bid = int(getattr(book, "best_yes_bid", 0) or 0)
            best_ask = int(getattr(book, "best_yes_ask", 0) or 0)
        else:
            best_bid = int(getattr(book, "best_no_bid", 0) or 0)
            best_ask = int(getattr(book, "best_no_ask", 0) or 0)

        # 2026-04-29 v3 (Claude per user — "we should probably just enter
        # at market and accept the free money for the copy trades"):
        # The 100% WR wallet is the filter. Whatever Kalshi is asking,
        # we pay. No edge calculations, no flat limits, no walk-up.
        # The wallet's selectivity is trusted to mean the trade is good.
        #
        # 2026-04-29 v4 (Claude per user — "Contrarian wallets with a 100%
        # WR??"): per-tier pricing. CERTAINTY pays whatever the ask is
        # (current behavior). MID and CONTRARIAN cap at poly_price +
        # premium — if Kalshi has already run past the wallet's entry
        # by more than the premium, the contrarian's edge has been
        # priced in and we'd be chasing.
        max_entry = int(_uc("WALLET_COPY_MAX_ENTRY_C", 99))
        tier = signal.get("tier", TIER_CERTAINTY)
        tier_premium = _tier_premium_c(tier)  # None for CERTAINTY
        poly_c = int(round(signal["poly_price"] * 100))
        # Hard ceiling
        if best_ask > 0:
            entry_price = min(best_ask, max_entry)
        else:
            entry_price = max_entry
        # Per-tier poly-price relative cap
        if tier_premium is not None:
            poly_cap = poly_c + int(tier_premium)
            if best_ask > 0 and best_ask > poly_cap:
                logger.warning(
                    "terminal_copy [%s] CHASE-SKIP: wallet=%s (%s) "
                    "side=%s poly=%dc kalshi_ask=%dc > poly+%dc cap "
                    "(=%dc) — Kalshi has already run past, no edge",
                    tier, signal["wallet"][:12], signal["username"][:18],
                    side.upper(), poly_c, best_ask, int(tier_premium),
                    poly_cap,
                )
                return
            entry_price = min(entry_price, poly_cap)
        entry_price = max(1, entry_price)

        # Sizing: $WALLET_COPY_DOLLAR_SIZE / entry_price
        dollar_size = float(_uc("WALLET_COPY_DOLLAR_SIZE", 20.0))
        contracts = max(1, int(round(dollar_size * 100 / entry_price)))
        # Hard cap from user_config
        max_ct = int(_uc("WALLET_COPY_MAX_CONTRACTS", 200))
        contracts = min(contracts, max_ct)

        # Trades-enabled gate (lets us run observability-only first)
        if not bool(_uc("WALLET_COPY_TRADES_ENABLED", False)):
            logger.warning(
                "terminal_copy [%s] SIGNAL (TRADES OFF): wallet=%s (%s) "
                "side=%s poly=%.3fx%.0f ticker=%s entry_target=%dc "
                "size=%dct ($%.2f) — would fire if WALLET_COPY_TRADES_"
                "ENABLED=True",
                tier, signal["wallet"][:12], signal["username"][:18],
                side.upper(), signal["poly_price"], signal["poly_size"],
                ticker[-15:], entry_price, contracts,
                contracts * entry_price / 100.0,
            )
            return

        # FIRE
        try:
            order = await self.engine._client.place_order(
                ticker=ticker, side=side, count=contracts,
                price=entry_price, action="buy",
            )
            filled = int(getattr(order, "filled_count", 0) or 0)
            oid = getattr(order, "order_id", "") or ""
            self._last_signal_window = ticker
            self._fires_today += 1
            logger.warning(
                "terminal_copy [%s] COPY-FIRE: wallet=%s (%s) side=%s "
                "poly=%.3fx%.0f → kalshi %s %dx @ %dc "
                "($%.2f) filled=%d order=%s [day=%d/%d]",
                tier, signal["wallet"][:12], signal["username"][:18],
                side.upper(), signal["poly_price"], signal["poly_size"],
                ticker[-15:], contracts, entry_price,
                contracts * entry_price / 100.0, filled, oid[:12],
                self._fires_today, max_per_day,
            )
        except Exception as e:
            logger.error("terminal_copy [%s] COPY-FIRE failed: %s", tier, e)

    async def _loop(self) -> None:
        """Main polling loop."""
        if not self.pool.addrs:
            self.pool.load()
        if not self.pool.addrs:
            logger.warning(
                "terminal_copy: no wallets loaded — copy engine idle. "
                "Generate data/terminal_wallets.json then restart."
            )
        # Wait for engine to fully start
        await asyncio.sleep(20)
        poll_s = float(_uc("WALLET_COPY_POLL_S", 2.5))
        async with aiohttp.ClientSession() as session:
            poller = TradePoller(session, self.pool)
            logger.warning(
                "terminal_copy: starting trade poller (interval=%.1fs, "
                "wallets=%d, trades_enabled=%s)",
                poll_s, len(self.pool.addrs),
                bool(_uc("WALLET_COPY_TRADES_ENABLED", False)),
            )
            # Wallet pool refresh every hour
            reload_interval = float(_uc("WALLET_COPY_RELOAD_S", 3600.0))
            last_reload = time.time()
            while True:
                try:
                    new = await poller.poll_once()
                    for t in new:
                        sig = _signal_qualifies(t, self.pool)
                        if sig is not None:
                            await self._execute_copy(sig)
                    if time.time() - last_reload >= reload_interval:
                        self.pool.load()
                        last_reload = time.time()
                except asyncio.CancelledError:
                    raise
                except Exception:
                    logger.exception("terminal_copy: loop iteration error")
                await asyncio.sleep(poll_s)


def start_terminal_copy(engine) -> Optional[asyncio.Task]:
    """Spawn the terminal-copy loop as a background task on engine startup.

    Returns the asyncio.Task or None if disabled.
    """
    if not bool(_uc("WALLET_COPY_ENGINE_ENABLED", False)):
        logger.info("terminal_copy: disabled via WALLET_COPY_ENGINE_ENABLED=False")
        return None
    tc = TerminalCopyEngine(engine)
    return asyncio.create_task(tc._loop(), name="terminal_copy_loop")
